name: formal
# either manually started, or on a schedule
on: [ push, workflow_dispatch, pull_request ]
jobs:
  formal:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3

    # install oss fpga tools for cocotb and iverilog
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: | 
        yosys --version

    # formal
    - name: formal
      run: |
        cd verilog/rtl/scan_controller
        sby -f scan_mux.sby
