name: tt_datasheet
# either manually started, or on a schedule
on: [ push, workflow_dispatch, pull_request ]
jobs:
  build_datasheet:
    env:
        GH_TOKEN:       ${{ secrets.GH_TOKEN }}
        GH_USERNAME:    ${{ secrets.GH_USERNAME }}

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out, and the tt_docs repo checked out
    - name: checkout repo
      uses: actions/checkout@v3
      with: 
        submodules: true

    # install the tt tools
    - name: checkout tt tools repo
      uses: actions/checkout@v3
      with:
        repository: tinytapeout/tt-support-tools
        ref: submission-tools
        path: tt

    # need python
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r tt/requirements.txt

    # fetch the repos
    - name: fetch all
      run: python ./tt/configure.py --clone-all --debug

    # pandoc deps
    - name: Pandoc deps
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y pandoc texlive-xetex

    # dump pdf
    - name: update datasheet
      run: python ./tt/configure.py --dump-markdown datasheet.md --dump-pdf datasheet.pdf

    # archive the PDF
    - name: Archive PDF
      uses: actions/upload-artifact@v3
      with:
          name: PDF
          path: datasheet.pdf
